-- ZUCCA勤怠のクラウド同期端末を、Supabase Authユーザー単位で管理する。
create table if not exists public.device_registrations (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  device_id text not null,
  device_name text not null default '',
  device_type text not null check (device_type in ('punch', 'admin')),
  created_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  unique (user_id, device_id)
);

create index if not exists device_registrations_user_type_idx
  on public.device_registrations (user_id, device_type);

alter table public.device_registrations enable row level security;

drop policy if exists "Users can view own device registrations" on public.device_registrations;
create policy "Users can view own device registrations"
  on public.device_registrations for select
  to authenticated
  using (user_id = auth.uid());

-- 同時登録でも上限を超えないよう、ユーザーごとのtransaction advisory lock内で判定する。
create or replace function public.register_device(
  p_device_id text,
  p_device_type text,
  p_device_name text default ''
) returns public.device_registrations
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_user_id uuid := auth.uid();
  v_registration public.device_registrations;
  v_count integer;
begin
  if v_user_id is null then raise exception 'authentication_required'; end if;
  if nullif(btrim(p_device_id), '') is null then raise exception 'device_id_required'; end if;
  if p_device_type not in ('punch', 'admin') then raise exception 'invalid_device_type'; end if;

  perform pg_advisory_xact_lock(hashtextextended(v_user_id::text, 0));

  -- 同じ端末の再接続は枠を追加消費せず、名称と最終確認時刻だけ更新する。
  select * into v_registration
    from public.device_registrations
    where user_id = v_user_id and device_id = p_device_id;

  if found and v_registration.device_type = p_device_type then
    update public.device_registrations
      set device_name = left(coalesce(nullif(btrim(p_device_name), ''), device_name), 60),
          last_seen_at = now()
      where id = v_registration.id returning * into v_registration;
    return v_registration;
  end if;

  select count(*) into v_count from public.device_registrations
    where user_id = v_user_id and device_type = p_device_type;
  if p_device_type = 'punch' and v_count >= 1 then raise exception 'device_limit_punch'; end if;
  if p_device_type = 'admin' and v_count >= 2 then raise exception 'device_limit_admin'; end if;

  insert into public.device_registrations (user_id, device_id, device_name, device_type)
  values (v_user_id, p_device_id, left(coalesce(nullif(btrim(p_device_name), ''), '名称未設定'), 60), p_device_type)
  on conflict (user_id, device_id) do update
    set device_name = excluded.device_name,
        device_type = excluded.device_type,
        last_seen_at = now()
  returning * into v_registration;
  return v_registration;
end;
$$;

create or replace function public.unregister_device(p_device_id text)
returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_user_id uuid := auth.uid();
  v_deleted integer;
begin
  if v_user_id is null then raise exception 'authentication_required'; end if;
  delete from public.device_registrations
    where user_id = v_user_id and device_id = p_device_id;
  get diagnostics v_deleted = row_count;
  return v_deleted > 0;
end;
$$;

revoke all on function public.register_device(text, text, text) from public;
revoke all on function public.unregister_device(text) from public;
grant execute on function public.register_device(text, text, text) to authenticated;
grant execute on function public.unregister_device(text) to authenticated;
grant select on public.device_registrations to authenticated;
